<a href="https://colab.research.google.com/github/rahulku91058/Training-AIML/blob/main/RNN/RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!git clone https://github.com/rahulku91058/Training-AIML.git
%cd Training-AIML/RNN

Cloning into 'Training-AIML'...
remote: Enumerating objects: 177, done.
remote: Counting objects: 100% (177/177), done.
remote: Compressing objects: 100% (156/156), done.
remote: Total 177 (delta 67), reused 86 (delta 17), pack-reused 0 (from 0)
Receiving objects: 100% (177/177), 40.30 MiB | 18.91 MiB/s, done.
Resolving deltas: 100% (67/67), done.
/content/Training-AIML/RNN


In [3]:
from tensorflow.keras.layers import SimpleRNN, Embedding, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [4]:
print(dir(Tokenizer))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_api_export_path', '_api_export_symbol_id', 'fit_on_sequences', 'fit_on_texts', 'get_config', 'sequences_to_matrix', 'sequences_to_texts', 'sequences_to_texts_generator', 'texts_to_matrix', 'texts_to_sequences', 'texts_to_sequences_generator', 'to_json']


In [7]:
from tensorflow.keras.models import Sequential
import tensorflow as tf
# Sample text data
data=["I love programing",
      "Programming is fun",
      "Deep learning is powerful",
      "I love deep learning"]

# Tokenize and sequence data
tokenizer = Tokenizer()
tokenizer.fit_on_texts(data)
sequences = tokenizer.texts_to_sequences(data)
print(sequences)

[[1, 2, 6], [7, 3, 8], [4, 5, 3, 9], [1, 2, 4, 5]]


In [8]:
# Prepare input and output for RNN
vocab_size = len(tokenizer.word_index) + 1
input_sequences = []
for sequence in sequences:
    for i in range(1, len(sequence)):
        input_sequences.append(sequence[:i+1])

In [16]:
# Pad sequential
max_length = max([len(seq) for seq in input_sequences])
input_sequences = pad_sequences(input_sequences, maxlen=max_length, padding='pre')
#print(input_sequences)

[[0 0 1 2]
 [0 1 2 6]
 [0 0 7 3]
 [0 7 3 8]
 [0 0 4 5]
 [0 4 5 3]
 [4 5 3 9]
 [0 0 1 2]
 [0 1 2 4]
 [1 2 4 5]]


In [15]:
# Split input x and target (y)
X = input_sequences[:,:-1]
y = input_sequences[:,-1]
X,y

(array([[0, 0, 1],
        [0, 1, 2],
        [0, 0, 7],
        [0, 7, 3],
        [0, 0, 4],
        [0, 4, 5],
        [4, 5, 3],
        [0, 0, 1],
        [0, 1, 2],
        [1, 2, 4]], dtype=int32),
 array([2, 6, 3, 8, 5, 3, 9, 2, 4, 5], dtype=int32))

In [17]:
# Build RNN model
model = Sequential([
    Embedding(vocab_size, 10, input_length=max_length-1),
    SimpleRNN(50, activation='tanh'),
    Dense(vocab_size, activation='softmax')
])


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [18]:
# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [20]:
# train the model
model.fit(X, y, epochs=100, verbose=1)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.2000 - loss: 2.2850
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.2000 - loss: 2.2741
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 2.2631
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5000 - loss: 2.2521
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5000 - loss: 2.2409
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7000 - loss: 2.2294
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.7000 - loss: 2.2177
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7000 - loss: 2.2056
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.8000 - loss: 2.1931
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.8000 - loss: 2.1801
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.8000 - loss: 2.1666
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.8000 - loss

In [26]:
# Test the model
input_text = "I love deep"
tokenized_input = tokenizer.texts_to_sequences([input_text])[0]
tokenized_input = pad_sequences([tokenized_input], maxlen=max_length-1, padding='pre')

In [27]:
# Predict
predicted_word = model.predict(tokenized_input)
predicted_word_index = tf.argmax(predicted_word, axis=-1).numpy()[0]
print("Predicted Next Word:",tokenizer.index_word[predicted_word_index])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step
Predicted Next Word: learning
