In [1]:
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score
import numpy as np  # numerical processing
import pandas as pd # dataframes

train_data = pd.read_csv("trainMatrixModified.txt",sep='\t', header=None)
test_data = pd.read_csv("testMatrixModified.txt",sep='\t', header=None)
train_class = pd.read_csv("trainClasses.txt",sep='\t', header=None)
test_class = pd.read_csv("testClasses.txt",sep='\t', header=None)

X_train=train_data.T
X_test=test_data.T
y_train=train_class[1]
y_test=test_class[1]

In [2]:
print("01: Logistic Regression Classifiers from Scikit-learn")
from sklearn.linear_model import LogisticRegression
#Create the machine learning classifier object
clf = LogisticRegression() 
clf.fit(X_train, y_train)
#predict labels for all the sentences
pred_y = clf.predict(X_test) #predicting based on X
#print("Predicted labels:", pred_y)
#Calculate accuracy, confusion_matrix and classification_report on our training data
print("01: Classification Report on training data:\n", classification_report(y_test, pred_y))
print("01: Mean accuracy on training data:\n", accuracy_score(y_test, pred_y))
print("01: Confusion Matrix on training data:\n", confusion_matrix(y_test, pred_y))

01: Logistic Regression Classifiers from Scikit-learn
01: Classification Report on training data:
               precision    recall  f1-score   support

           0       0.96      1.00      0.98        99
           1       1.00      0.96      0.98       101

    accuracy                           0.98       200
   macro avg       0.98      0.98      0.98       200
weighted avg       0.98      0.98      0.98       200

01: Mean accuracy on training data:
 0.98
01: Confusion Matrix on training data:
 [[99  0]
 [ 4 97]]


In [3]:
print("02: Support Vector Classifiers from Scikit-learn")
from sklearn.svm import SVC
#Create the machine learning classifier object
clf = SVC()
clf.fit(X_train, y_train)
#predict labels for all the sentences
pred_y = clf.predict(X_test) #predicting based on X
#print("Predicted labels:", pred_y)
#Calculate accuracy, confusion_matrix and classification_report on our training data
print("02: Classification Report on training data:\n", classification_report(y_test, pred_y))
print("02: Mean accuracy on training data:\n", accuracy_score(y_test, pred_y))
print("02: Confusion Matrix on training data:\n", confusion_matrix(y_test, pred_y))

02: Support Vector Classifiers from Scikit-learn
02: Classification Report on training data:
               precision    recall  f1-score   support

           0       0.82      1.00      0.90        99
           1       1.00      0.78      0.88       101

    accuracy                           0.89       200
   macro avg       0.91      0.89      0.89       200
weighted avg       0.91      0.89      0.89       200

02: Mean accuracy on training data:
 0.89
02: Confusion Matrix on training data:
 [[99  0]
 [22 79]]


In [4]:
print("03: Decision Tree Classifiers from Scikit-learn")
from sklearn.tree import DecisionTreeClassifier
#Create the machine learning classifier object
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)
#predict labels for all the sentences
pred_y = clf.predict(X_test) #predicting based on X
#print("Predicted labels:", pred_y)
#Calculate accuracy, confusion_matrix and classification_report on our training data
print("03: Classification Report on training data:\n", classification_report(y_test, pred_y))
print("03: Mean accuracy on training data:\n", accuracy_score(y_test, pred_y))
print("03: Confusion Matrix on training data:\n", confusion_matrix(y_test, pred_y))

03: Decision Tree Classifiers from Scikit-learn
03: Classification Report on training data:
               precision    recall  f1-score   support

           0       0.85      0.95      0.90        99
           1       0.94      0.84      0.89       101

    accuracy                           0.90       200
   macro avg       0.90      0.90      0.89       200
weighted avg       0.90      0.90      0.89       200

03: Mean accuracy on training data:
 0.895
03: Confusion Matrix on training data:
 [[94  5]
 [16 85]]


In [5]:
print("04: KNN classifiers from Scikit-learn")
from sklearn.neighbors import KNeighborsClassifier
#Create the machine learning classifier object
clf = KNeighborsClassifier(n_neighbors=3) 
clf.fit(X_train, y_train)
X_test = np.ascontiguousarray(X_test)
#predict labels for all the sentences
pred_y = clf.predict(X_test) #predicting based on X
#print("Predicted labels:", pred_y)
#Calculate accuracy, confusion_matrix and classification_report on our training data
print("04: Classification Report on training data:\n", classification_report(y_test, pred_y))
print("04: Mean accuracy on training data:\n", accuracy_score(y_test, pred_y))
print("04: Confusion Matrix on training data:\n", confusion_matrix(y_test, pred_y))

04: KNN classifiers from Scikit-learn
04: Classification Report on training data:
               precision    recall  f1-score   support

           0       0.77      0.86      0.81        99
           1       0.84      0.74      0.79       101

    accuracy                           0.80       200
   macro avg       0.80      0.80      0.80       200
weighted avg       0.80      0.80      0.80       200

04: Mean accuracy on training data:
 0.8
04: Confusion Matrix on training data:
 [[85 14]
 [26 75]]


In [6]:
print("05: Nearest Centroid (1st case) from Scikit-learn")
from sklearn.neighbors import NearestCentroid
#Create the machine learning classifier object
clf = NearestCentroid(shrink_threshold=None)
clf.fit(X_train, y_train)
#predict labels for all the sentences
pred_y = clf.predict(X_test) #predicting based on X
#print("Predicted labels:", pred_y)
#Calculate accuracy, confusion_matrix and classification_report on our training data
print("05: Classification Report on training data:\n", classification_report(y_test, pred_y))
print("05: Mean accuracy on training data:\n", accuracy_score(y_test, pred_y))
print("05: Confusion Matrix on training data:\n", confusion_matrix(y_test, pred_y))

05: Nearest Centroid (1st case) from Scikit-learn
05: Classification Report on training data:
               precision    recall  f1-score   support

           0       1.00      0.88      0.94        99
           1       0.89      1.00      0.94       101

    accuracy                           0.94       200
   macro avg       0.95      0.94      0.94       200
weighted avg       0.95      0.94      0.94       200

05: Mean accuracy on training data:
 0.94
05: Confusion Matrix on training data:
 [[ 87  12]
 [  0 101]]


In [7]:
print("06: Nearest Centroid (2nd case) from Scikit-learn")
from sklearn.neighbors import NearestCentroid
#Create the machine learning classifier object
clf = NearestCentroid(shrink_threshold=0.2)
clf.fit(X_train, y_train)
#predict labels for all the sentences
pred_y = clf.predict(X_test) #predicting based on X
#print("Predicted labels:", pred_y)
#Calculate accuracy, confusion_matrix and classification_report on our training data
print("06: Classification Report on training data:\n", classification_report(y_test, pred_y))
print("06: Mean accuracy on training data:\n", accuracy_score(y_test, pred_y))
print("06: Confusion Matrix on training data:\n", confusion_matrix(y_test, pred_y))

06: Nearest Centroid (2nd case) from Scikit-learn
06: Classification Report on training data:
               precision    recall  f1-score   support

           0       1.00      0.91      0.95        99
           1       0.92      1.00      0.96       101

    accuracy                           0.95       200
   macro avg       0.96      0.95      0.95       200
weighted avg       0.96      0.95      0.95       200

06: Mean accuracy on training data:
 0.955
06: Confusion Matrix on training data:
 [[ 90   9]
 [  0 101]]
